PATHFINDER_DEBUG_NODE_ID = "pathFinderDebug"
PATHFINDER_NODE_ID = "pathFinder"

PATHFINDER_INPUT_TOPIC = "pathFinderInput"

INITIATE_FINDPATH_SERVICE = "initiateFindPath"
STEP_FINDPATH_SERVICE = "stepFindPath"