ROS_QUEUE_SIZE = 10

PATHFINDER_DEBUG_NODE_ID = "pathFinderDebug"
PATHFINDER_NODE_ID = "pathFinder"

PATHFINDER_INPUT_TOPIC = "pathFinderInput"
PATHFINDER_SOLUTION_TOPIC = "pathFinderSolution"
PATHFINDER_DEBUG_TOPIC = "pathFinderDebug"
FLIGHT_CONTROLLER_SOLUTION_TOPIC = "flightControllerSolutionTopic"

SUBMIT_PROBLEM_SERVICE = "submitProblem"
STEP_PROBLEM_SERVICE = "stepProblem"
SOLVE_PROBLEM_SERVICE = "solveProblem"
